# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoyaRxSwift
	
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '5.0.0'
  pod "RxGesture", '4.0.3'
  pod 'Action', '5.0.0'
  pod 'Moya/RxSwift', '~> 15.0'
  #extension
  pod 'SwifterSwift', '5.2.0'
  #utilities
  pod 'AsyncSwift', '2.0.4'
  #log
  pod 'SwiftyBeaver', '1.9.5'
  #autolayout
  pod 'SnapKit', '5.0.1'
  pod 'IQKeyboardManager'
  #MVVM
  pod 'MVVM-Swift'
  #database
  pod 'RealmSwift'
  #mapper
  pod 'ObjectMapper'

  target 'MoyaRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoyaRxSwiftUITests' do
    # Pods for testing
  end

end
